version: '3'

tasks:
  install-deps:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  get-deps:
    cmds:
      - go get -u google.golang.org/protobuf/cmd/protoc-gen-go
      - go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc

  generate:
    cmds:
      - task: generate-note-api

  generate-note-api:
    cmds:
      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/apartment_v1')) { New-Item -ItemType Directory -Path 'pkg/grpc/apartment_v1' }"
      - |
        protoc --proto_path proto/apartment_v1 \
        --go_out=pkg/grpc/apartment_v1 --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/apartment_v1 --go-grpc_opt=paths=source_relative \
        proto/apartment_v1/apartment.proto
