// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: apartment.proto

package apartment_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApartmentService_NewApartment_FullMethodName    = "/apartment_v1.ApartmentService/NewApartment"
	ApartmentService_UpdateApartment_FullMethodName = "/apartment_v1.ApartmentService/UpdateApartment"
	ApartmentService_RemoveApartment_FullMethodName = "/apartment_v1.ApartmentService/RemoveApartment"
)

// ApartmentServiceClient is the client API for ApartmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApartmentServiceClient interface {
	NewApartment(ctx context.Context, in *NewApartmentRequest, opts ...grpc.CallOption) (*NewApartmentResponse, error)
	UpdateApartment(ctx context.Context, in *UpdateApartmentRequest, opts ...grpc.CallOption) (*UpdateApartmentResponse, error)
	RemoveApartment(ctx context.Context, in *RemoveApartmentRequest, opts ...grpc.CallOption) (*RemoveApartmentResponse, error)
}

type apartmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApartmentServiceClient(cc grpc.ClientConnInterface) ApartmentServiceClient {
	return &apartmentServiceClient{cc}
}

func (c *apartmentServiceClient) NewApartment(ctx context.Context, in *NewApartmentRequest, opts ...grpc.CallOption) (*NewApartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewApartmentResponse)
	err := c.cc.Invoke(ctx, ApartmentService_NewApartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apartmentServiceClient) UpdateApartment(ctx context.Context, in *UpdateApartmentRequest, opts ...grpc.CallOption) (*UpdateApartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateApartmentResponse)
	err := c.cc.Invoke(ctx, ApartmentService_UpdateApartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apartmentServiceClient) RemoveApartment(ctx context.Context, in *RemoveApartmentRequest, opts ...grpc.CallOption) (*RemoveApartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveApartmentResponse)
	err := c.cc.Invoke(ctx, ApartmentService_RemoveApartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApartmentServiceServer is the server API for ApartmentService service.
// All implementations must embed UnimplementedApartmentServiceServer
// for forward compatibility.
type ApartmentServiceServer interface {
	NewApartment(context.Context, *NewApartmentRequest) (*NewApartmentResponse, error)
	UpdateApartment(context.Context, *UpdateApartmentRequest) (*UpdateApartmentResponse, error)
	RemoveApartment(context.Context, *RemoveApartmentRequest) (*RemoveApartmentResponse, error)
	mustEmbedUnimplementedApartmentServiceServer()
}

// UnimplementedApartmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApartmentServiceServer struct{}

func (UnimplementedApartmentServiceServer) NewApartment(context.Context, *NewApartmentRequest) (*NewApartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewApartment not implemented")
}
func (UnimplementedApartmentServiceServer) UpdateApartment(context.Context, *UpdateApartmentRequest) (*UpdateApartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateApartment not implemented")
}
func (UnimplementedApartmentServiceServer) RemoveApartment(context.Context, *RemoveApartmentRequest) (*RemoveApartmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveApartment not implemented")
}
func (UnimplementedApartmentServiceServer) mustEmbedUnimplementedApartmentServiceServer() {}
func (UnimplementedApartmentServiceServer) testEmbeddedByValue()                          {}

// UnsafeApartmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApartmentServiceServer will
// result in compilation errors.
type UnsafeApartmentServiceServer interface {
	mustEmbedUnimplementedApartmentServiceServer()
}

func RegisterApartmentServiceServer(s grpc.ServiceRegistrar, srv ApartmentServiceServer) {
	// If the following call pancis, it indicates UnimplementedApartmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApartmentService_ServiceDesc, srv)
}

func _ApartmentService_NewApartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewApartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServiceServer).NewApartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApartmentService_NewApartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServiceServer).NewApartment(ctx, req.(*NewApartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApartmentService_UpdateApartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServiceServer).UpdateApartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApartmentService_UpdateApartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServiceServer).UpdateApartment(ctx, req.(*UpdateApartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApartmentService_RemoveApartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveApartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApartmentServiceServer).RemoveApartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApartmentService_RemoveApartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApartmentServiceServer).RemoveApartment(ctx, req.(*RemoveApartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApartmentService_ServiceDesc is the grpc.ServiceDesc for ApartmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApartmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apartment_v1.ApartmentService",
	HandlerType: (*ApartmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewApartment",
			Handler:    _ApartmentService_NewApartment_Handler,
		},
		{
			MethodName: "UpdateApartment",
			Handler:    _ApartmentService_UpdateApartment_Handler,
		},
		{
			MethodName: "RemoveApartment",
			Handler:    _ApartmentService_RemoveApartment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apartment.proto",
}
